### PR TITLE
Javascript tutorial

### PR DESCRIPTION
**Pull request by Rishav1707**
# 🛠️ Fixes issue #72 
# 📇 Changes proposed 
- Added resources for `Javascript`
# ✅ Check List (Mark all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [ ] This PR contains changes in the documentation
- [ ] This PR contains changes in the Code of the project
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
java

### CODE REVIEW

**Comment by hasnainmakada-99** [comment]
Hey, @Rishav1707 I would like to request some more resources from you to add in sequences (Beginner to expert level). It could be anything such as blog posts which can be useful for beginners

**Comment by Rishav1707** [comment]
> Hey, @Rishav1707 I would like to request some more resources from you to add in sequences (Beginner to expert level). It could be anything such as blog posts which can be useful for beginners

Okk

**Comment by hasnainmakada-99** [comment]
Hello @Rishav1707 ?

**Comment by Rishav1707** [comment]
> Hello @Rishav1707 ?

Yes @hasnainmakada-99

**Comment by hasnainmakada-99** [comment]
Have you made the changes @Rishav1707

**Comment by Rishav1707** [comment]
> Have you made the changes @Rishav1707

Yeah, the changes were already made.

**Comment by hasnainmakada-99** [comment]
See the review which I have started @Rishav1707 , The changes are not made

**Comment by Rishav1707** [comment]
> See the review which I have started @Rishav1707 , The changes are not made

which review? and from where?

**Comment by hasnainmakada-99** [comment]
Look out in the files changed tab
image

**Comment by Rishav1707** [comment]
> Look out in the files changed tab image

**Pull request closed without merging**
