### PR TITLE
New Resources added to Machine Learning

### PR DESCRIPTION
**Pull request by yugborana**
# 🛠️ Fixes issue #107 
# 📇 Changes proposed 
# ✅ Check List (Mark all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [ ] This PR contains changes in the documentation
- [x] This PR contains changes in the Code of the project
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by hasnainmakada-99** [comment]
Please refer the issue which you're trying to solve @yugborana

**Comment by yugborana** [comment]
addition of new resources to machine-learning-resources.md file

**Comment by hasnainmakada-99** [comment]
Please refer to the issue which you are trying to solve @yugborana 

Here 👇 
image

**Review by hasnainmakada-99 — CHANGES_REQUESTED** [review]
The thumbnail sizes are too big, Keep the sizes to 320Wx180H. I suggest edit the thumbnails with the help of canva

**Comment by yugborana** [comment]
ok I will try to do that

**Pull request merged**
