### PR TITLE
added web_dev_resources.json

### PR DESCRIPTION
**Pull request by SahilSinghTomar**
# 🛠️ Partially Fixes issue #164 
# 📇 Changes proposed 
- Added Web Development JSON Resources file.

# ✅ Check List (Mark all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] This PR contains changes in the Code of the project
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
I will further JSON resources in some time.

### CODE REVIEW

**Review by hasnainmakada-99 — CHANGES_REQUESTED** [review]
You have to create a separate directory for the storage of JSON files @SahilSinghTomar, please redo it and raise a fresh pr again

**Comment by SahilSinghTomar** [comment]
I should close this pr and open another pull request ?? @hasnainmakada-99

**Comment by SahilSinghTomar** [comment]
Add a JSON Resources > Web Dev Resources.  Are you saying to do like this ?? @hasnainmakada-99

**Comment by hasnainmakada-99** [comment]
> Add a JSON Resources > Web Dev Resources. Are you saying to do like this ?? @hasnainmakada-99

Not like that, Create a new directory inside the root folder of this project, named Resources and create .json files inside that directory only, so that it doesn't get conflicted with other files @SahilSinghTomar

**Comment by SahilSinghTomar** [comment]
ok, Will do it sure.

**Comment by SahilSinghTomar** [comment]
## Created new Pull Request #184

## Closing this PR.

**Pull request closed without merging**
