### PR TITLE
Created PR template

### PR DESCRIPTION
**Pull request by KlausMikhaelson**
Created PR template and now working on the issue template.
let me know if there are any changes needed !

### CODE REVIEW

**Comment by hasnainmakada-99** [comment]
> Created PR template and now working on the issue template. let me know if there are any changes needed !

Make both the changes and raise the PR when both the changes are made, I'll review it tomorrow @KlausMikhaelson

**Comment by KlausMikhaelson** [comment]
just adding the reference of the issue here ! #3

**Comment by hasnainmakada-99** [comment]
Hey @KlausMikhaelson I think that you don't know how to create templates, Don't worry I am providing you the links as reference to work on the issue

PR Template reference : https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/.github/PULL_REQUEST_TEMPLATE.md

Issue Template reference : https://github.com/Dun-sin/smartsearch/tree/main/.github/ISSUE_TEMPLATE

**Comment by hasnainmakada-99** [comment]
And try to raise only one PR and not separate ones @KlausMikhaelson

**Comment by KlausMikhaelson** [comment]
@hasnainmakada-99 actually I created some of those templates in that repo you shared, I literally completely misunderstood what I was suppose to do lol, just don't merge it will create a pr tomorrow I thought I was suppose to add instructions my bad !

**Comment by hasnainmakada-99** [comment]
It's completely fine, do it tomorrow @KlausMikhaelson

**Pull request closed without merging**
