### PR TITLE
Worked on issue #30

### PR DESCRIPTION
**Pull request by Busayo-ojo**
# 🛠️ Fixed issue #30
# 📇 Change Proposed [Added resources for Data Structures and Algorithms](https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/issues/30#top) 
# ✅ Check List (Mark all the applicable boxes)

- [x] My code follows the code style for this project.
- [x] This PR does not contain plagiarized content.
- [x] This PR contains changes in the documentation
- [x] This PR contains changes in the Code of the project
- [x] The title of my pull request is a short description of the requested changes.

# 📷 Screenshots
image

### CODE REVIEW

**Comment by hasnainmakada-99** [comment]
Please refer to the issue properly and keep the title according to the issue @Busayo-ojo

**Comment by Busayo-ojo** [comment]
@hasnainmakada-99 Please check now

**Review by hasnainmakada-99 — COMMENTED** [review]
Looks good to me 👍

**Review by hasnainmakada-99 — APPROVED** [review]

**Comment by hasnainmakada-99** [comment]
@all-contributors please add @Busayo-ojo as a contributor of tutorials

**Pull request merged**
