### PR TITLE
three new resources added to machine learning

### PR DESCRIPTION
**Pull request by alaminrifat**
# 🛠️ Fixes issue #90
# 📇 Changes proposed 
# ✅ Check List (Mark all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [ ] This PR contains changes in the documentation
- [x] This PR contains changes in the Code of the project
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
- Three new resources (10,11,12) were added to the machine learning page. 

## 📷 Screenshots
image

### CODE REVIEW

**Comment by hasnainmakada-99** [comment]
Please refer the issue in the PR @alaminrifat

**Comment by alaminrifat** [comment]
I don't understand your comment, @hasnainmakada-99

**Comment by hasnainmakada-99** [comment]
You have to mention the Issue number which you are fixing @alaminrifat ⬇️ 
image

**Comment by alaminrifat** [comment]
I've updated the issue number, please check @hasnainmakada-99

**Review by Frenziecodes — APPROVED** [review]

**Review by hasnainmakada-99 — APPROVED** [review]
Looks good to me, Thanks for contributing to OWSH @alaminrifat

**Comment by hasnainmakada-99** [comment]
@all-contributors, please add @alaminrifat as a contributor of tutorials

**Comment by hasnainmakada-99** [comment]
@all-contirbutors please add @alaminrifat as a contributor of tutorials

**Comment by hasnainmakada-99** [comment]
@all-contributors please add @alaminrifat as a contributor of tutorials

**Pull request merged**
