### PR TITLE
Updated readme

### PR DESCRIPTION
**Pull request by AdebayoIbrahim**
# ✅ Check List (Mark all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] This PR contains changes in the documentation
- [x] This PR contains changes in the Code of the project
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

This PR contains some update to the read-me on running the project locally

hasnain-readme

### CODE REVIEW

**Comment by AdebayoIbrahim** [comment]
Kindly help me review this update @hasnainmakada-99

**Comment by hasnainmakada-99** [comment]
So sorry for the late reply @AdebayoIbrahim, But I'll review it and get back to you by the end of this week

Currently dealing with my college exams, that's why

**Review by hasnainmakada-99 — APPROVED** [review]
looks good @AdebayoIbrahim

**Comment by AdebayoIbrahim** [comment]
Thanks @hasnainmakada-99

**Pull request merged**
