### PR TITLE
Created pull request template

### PR DESCRIPTION
**Pull request by KlausMikhaelson**

### CODE REVIEW

**Review by hasnainmakada-99 — APPROVED** [review]
LGTM

**Comment by KlausMikhaelson** [comment]
sorry for being late went to aws community days in another state and when I came back I got food poison... but all good now ! will create the issue one as well just getting myself familiar with yml first

**Comment by hasnainmakada-99** [comment]
> sorry for being late went to aws community days in another state and when I came back I got food poison... but all good now ! will create the issue one as well just getting myself familiar with yml first

Completely fine, No worries and take your time

**Comment by hasnainmakada-99** [comment]
@all-contributors please add @KlausMikhaelson  for code

**Pull request merged**
