### PR TITLE
Html branch

### PR DESCRIPTION
**Pull request by AdebayoIbrahim**
# 📇 Created new branch and added html reference list

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] This PR contains changes in the Code of the project
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by AdebayoIbrahim** [comment]
I have added an html branch @hasnainmakada-99

**Comment by yung-coder** [comment]
> I have added an html branch @hasnainmakada-99

can you mention for which issue this pr is...

**Comment by AdebayoIbrahim** [comment]
> > I have added an html branch @hasnainmakada-99
> 
> can you mention for which issue this pr is...

I wants to add new HTML Learning resource

**Review by hasnainmakada-99 — APPROVED** [review]
Looks good to me, Thanks for contributing to oswh @AdebayoIbrahim

**Pull request merged**
