### PR TITLE
Enhanced README.md

### PR DESCRIPTION
**Pull request by the-amazing-atharva**
# 🛠️ Fixes issue #59
# 📇 Changes proposed  
added nice designs and lists/paragraphs to the README.md
# ✅ Check List (Mark all the applicable boxes)

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] This PR contains changes in the documentation
- [ ] This PR contains changes in the Code of the project
- [X] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

 Updated yesterday's attempt and further improved the look of the README.md

## 📷 Screenshots
image

### CODE REVIEW

**Comment by the-amazing-atharva** [comment]
Hey @hasnainmakada-99 ,
Do let me know your thoughts !!

**Review by hasnainmakada-99 — APPROVED** [review]
Looks good to me

**Comment by hasnainmakada-99** [comment]
@all-contributors please add @the-amazing-atharva as a contributor of ideas

**Comment by the-amazing-atharva** [comment]
Thanks for the opportunity bro !!

**Comment by hasnainmakada-99** [comment]
> Thanks for the opportunity bro !!

You're welcome

**Comment by hasnainmakada-99** [comment]
Make sure to tell other people too  and IF you liked my project, make sure to give us a star ⭐

**Comment by the-amazing-atharva** [comment]
Sure

**Comment by the-amazing-atharva** [comment]
Can I tweet about my contribution?

**Comment by hasnainmakada-99** [comment]
Ya sure

**Comment by the-amazing-atharva** [comment]
Thanks once again

**Pull request merged**
