### PR TITLE
Updated machine-learning-resources.md

### PR DESCRIPTION
**Pull request by vaibhavx42**
Added courses, Playgrounds  to machine-learning-resources.md

### CODE REVIEW

**Comment by hasnainmakada-99** [comment]
Hey @vaibhavx42 I'll review the pr by tomorrow, sorry for the inconveniences caused, and please refer this pr with its corresponding issue number

**Comment by hasnainmakada-99** [comment]
Hey @vaibhavx42 please reference this PR with the issue which you are solving

**Comment by vaibhavx42** [comment]
> Hey @vaibhavx42 please reference this PR with the issue which you are solving

Hey @hasnainmakada-99 issue number is **31** adding machine learning resources.
**#31**

**Comment by hasnainmakada-99** [comment]
Thanks for contributing to OSWH @vaibhavx42

**Review by hasnainmakada-99 — APPROVED** [review]
LGTM

**Comment by hasnainmakada-99** [comment]
@all-contributors please add @vaibhavx42 for tutorial

**Pull request merged**
