### PR TITLE
Made some changes to the README file

### PR DESCRIPTION
**Pull request by alok-38**
# 🛠️ Fixes issue #
# 📇 Changes proposed 
# ✅ Check List (Mark all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] This PR contains changes in the documentation
- [x] This PR contains changes in the Code of the project
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by alok-38 — COMMENTED** [review]
Added some border separator to increase readability of README

**Review by hasnainmakada-99 — COMMENTED** [review]
First, raise an issue of what you are trying to do and what changes would you like to make

**Comment by alok-38** [comment]
I would like to enhance the look of the README.md file by adding some colorful borders between sections to make it more readable

**Comment by hasnainmakada-99** [comment]
Please raise an issue for the same

**Comment by alok-38** [comment]
Okay

**Pull request closed without merging**
