### PR TITLE
[Enhancements] New Header

### PR DESCRIPTION
**Pull request by Umayarz18**
# 🛠️ Fixes issue #80 
# 📇 Changes proposed 
- BREAKING CHANGE: The Acherus Militant Light font is no longer present in header
- Adds icon from the header as SVG to allow colors to change based on current theme via `fill="currentColor"`
- Accomplishes header styles through markup 
- Title is done with `h1` tag with custom styles
# ✅ Check List (Mark all the applicable boxes)

- [ ] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] This PR contains changes in the documentation
- [x] This PR contains changes in the Code of the project
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
If you would really like to keep Acherus Militant Light as the font, you can now import it into `index.html` to use for the heading. This is the best approach as making the title part of the SVG results in a huuuge code bloat.

## 📷 Screenshots
Preview of README.md when using VSCode in the browser.
Screenshot (24)

### CODE REVIEW

**Review by hasnainmakada-99 — CHANGES_REQUESTED** [review]
Hey @Umayarz18 I think that you have to use the image tag and put the SVG file inside it, BTW you put the SVG format as a static asset inside the project

**Review by hasnainmakada-99 — CHANGES_REQUESTED** [review]
Set the SVG width to 200 and height to 120

Also set the font-weight to 500 of the text "Open Source with Hasnain"

**Comment by Umayarz18** [comment]
> Hey @Umayarz18 I think that you have to use the image tag and put the SVG file inside it, BTW you put the SVG format as a static asset inside the project

I tried the import as an image element with the src being the SVG previously. The issue with this approach is the SVG will render statically and be unable to change when a user changes from light or dark mode. The ability to change the fill color is only possible as a markup SVG in the `README.md` using `currentColor` in the `[fill` property](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fill#circle) 

When adding the changes to the live site using Chrome Dev Tools, I can see the dynamic change with an SVG. However, this is not possible with an img. 
Screenshot (25)
Screenshot (26)

**Comment by hasnainmakada-99** [comment]
> > Hey @Umayarz18 I think that you have to use the image tag and put the SVG file inside it, BTW you put the SVG format as a static asset inside the project
> 
> I tried the import as an image element with the src being the SVG previously. The issue with this approach is the SVG will render statically and be unable to change when a user changes from light or dark mode. The ability to change the fill color is only possible as a markup SVG in the `README.md` using `currentColor` in the `[fill` property](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fill#circle)
> 
> When adding the changes to the live site using Chrome Dev Tools, I can see the dynamic change with an SVG. However, this is not possible with an img. Screenshot (25) Screenshot (26)

Yeah Now I got it @Umayarz18

**Comment by hasnainmakada-99** [comment]
> Set the SVG width to 200 and height to 120
> 
> Also set the font-weight to 500 of the text "Open Source with Hasnain"

Please make this changes

**Comment by hasnainmakada-99** [comment]
Hey @Umayarz18, The SVG format is not able to properly render on The  GitHub repo so we have to switch towards the PNG format, If possible please select a colour theme which is both light and dark mode compatible and create a new header in that

**Comment by Umayarz18** [comment]
Hi @hasnainmakada-99, I see what you mean for GitHub. With light and dark modes being contrasts of each other, there is no good way to choose a color that works for both with it looking very off. 

I have a theory you can keep the SVG for the docs site in the README and keep a static image of the header to display for GitHub's README Preview. Will try that out to see if there's a balance to it so GH gets static one but the site get the dynamic one

**Review by hasnainmakada-99 — CHANGES_REQUESTED** [review]
Sorry this changes are not allowed, you have to create a new header in PNG format @Umayarz18

**Comment by Umayarz18** [comment]
I think your original header works just fine honestly. If there is a technical constraint to allowing themeability then it makes more sense to keep the original design. I'll close out this PR since it was discovered that PNG is the only way to have the header render for GitHub and creating a new theme-agnostic header PNG would be difficult to design effectively.

**Comment by hasnainmakada-99** [comment]
Yeah, No problem @Umayarz18

**Pull request closed without merging**
