### PR TITLE
Update: Changelog to include commits after January 28th 2023

### PR DESCRIPTION
**Pull request by at-the-vr**
# 🛠️ Fixes issue #133 
# 📇 Changes proposed 
- includes all the commits related to Documentation, bug fixes and feature related PRs after January 28th 2023
- couple of major commits included -- add Star badge([14d4c197](https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/commit/14d4c197d6836227d3b56ee0e65d022b12602783)), add docsify plugin for  search ([491cfe51](https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/commit/491cfe518cb4fd099ccd84e5de906ec80c39c531)), add issue template ([8d4f5a10](https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/commit/8d4f5a10c9049bbe87f6f6a67ac7b80a9ed5e107)), update README.md, Dockerfile and Docker workflow ([8dc5d405](https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/commit/8dc5d40503c4a07e4a9a7af0b44e1e7888353a55)) and more listed in changelog.md
# ✅ Check List (Mark all the applicable boxes), 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] This PR contains changes in the documentation
- [x] This PR contains changes in the Code of the project
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
I have deliberately kept the date undecided since I thought this file can have suggested fixes and changes, if everything's alright, then I will add the current date

## 📷 Screenshots
Not necessary

### CODE REVIEW

**Review by hasnainmakada-99 — APPROVED** [review]
Looks good to me @at-the-vr

**Comment by hasnainmakada-99** [comment]
@all-cotnributors please add @at-the-vr as a contributor of maintenance

**Comment by hasnainmakada-99** [comment]
@all-contributors please add @at-the-vr as a contributor of maintenance

**Comment by at-the-vr** [comment]
Hey hasnain, could you later edit the **date** in changelog.md ? Its not correct that's why

**Pull request merged**
