### PR TITLE
@hasnainmakada-99 try to modified your file how to contribute open source

### PR DESCRIPTION
**Pull request by Madhurchandran**
# 🛠️ Fixes issue #166 
# 📇 Changes proposed  modified your file with new one how to contribute to open source 
# ✅ Check List (Mark all the applicable boxes)

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] This PR contains changes in the documentation
- [X] This PR contains changes in the Code of the project
- [X] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
1. that my first pull request, I tried keeping file as simple.

### CODE REVIEW

**Review by hasnainmakada-99 — CHANGES_REQUESTED** [review]
Hey @Madhurchandran, you were not supposed to touch this file, I told you to create a new guide on how to set up this project locally on host machine and for that you were supposed to create a new file, No worries mistakes do happen 😀

**Comment by Madhurchandran** [comment]
@hasnainmakada-99  is anything wrong should I try again

**Comment by hasnainmakada-99** [comment]
@yung-coder, Please look into this 🙏🏻

**Comment by yung-coder** [comment]
@Madhurchandran You  have to create  a entirely new file  ...

**Comment by Madhurchandran** [comment]
@yung-coder so I created new file or not

**Comment by yung-coder** [comment]
> @yung-coder so I created new file or not

can you be more specific with docsify in the file ...

**Comment by hasnainmakada-99** [comment]
Sorry @Madhurchandran, We have solved the issue now, thanks for being in touch, because we think that the requirements were not that much clear to you

**Pull request closed without merging**
