### PR TITLE
Update web-development-resources.md

### PR DESCRIPTION
**Pull request by gabrysia694**
# 🛠️ Fixes issue #
# 📇 Changes proposed: I added 2 CSS resources to Web Development near other CSS resources, therefore I also changed numbering of the whole list so it makes sense.
# ✅ Check List (Mark all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] This PR contains changes in the documentation
- [x] This PR contains changes in the Code of the project
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by hasnainmakada-99 — CHANGES_REQUESTED** [review]
Removing the existing content is not approved, I suggest you redo the changes and make sure the thumbnail size is 320 X 180 @gabrysia97

**Comment by gabrysia694** [comment]
ok, just fixed it

**Review by hasnainmakada-99 — APPROVED** [review]
Looks good to me @gabrysia97

**Comment by hasnainmakada-99** [comment]
@all-contributors please add @gabrysia97 as a contributor of tutorial

**Pull request merged**
