### PR TITLE
Backend Development Resources Added.

### PR DESCRIPTION
**Pull request by munnokd**
# 🛠️ Fixes issue #103
# 📇 Changes proposed 
I added Some Backend Development Resources on the web development page.
And I also added my name in the readme contribution section.

### CODE REVIEW

**Review by hasnainmakada-99 — CHANGES_REQUESTED** [review]
The editing in Readme.md file is not allowed, please revert the changes from that file, rest looks good. @munnokd

**Comment by munnokd** [comment]
@hasnainmakada-99  now merge the pull request.

**Review by hasnainmakada-99 — APPROVED** [review]
Looks great, Thanks for contributing @munnokd

**Comment by hasnainmakada-99** [comment]
@all-contributors, please add @munnokd as a contributor of tutorials

**Comment by hasnainmakada-99** [comment]
@all-contributors please add @munnokd as a contributor of tutorials

**Pull request merged**
