### PR TITLE
Update data-structure-and-algorithms-resources.md

### PR DESCRIPTION
**Pull request by Vedeesh6**
Added some more useful resources

# 🛠️ Fixes issue #
# 📇 Changes proposed 
# ✅ Check List (Mark all the applicable boxes)

- [ ] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] This PR contains changes in the documentation
- [ ] This PR contains changes in the Code of the project
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by hasnainmakada-99** [comment]
Please raise an issue for the same @Vedeesh6 and reference it over here in this PR

**Comment by Vedeesh6** [comment]
Done #69

**Review by hasnainmakada-99 — APPROVED** [review]
Looks Good to me, Thanks for contributing to OSWH

**Comment by hasnainmakada-99** [comment]
@all-contributors please add @Vedeesh6 as a contributor of tutorial

**Pull request merged**
