### PR TITLE
Eddiehub image resized

### LINKED ISSUE #39: Fix images resolution in OpenSourceResources.md
The thumbnail of resources should be 320 x 180, redesign the thumbnails again with canva and upload it here

the directory structure to open source resources file is as follows,

[./pages/opensource-resources.md](https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/blob/main/pages/open-source-resources.md)

as for talking about the images, create a new folder inside the `pages` directory name `images` and paste the images over there itself

### PR DESCRIPTION
**Pull request by mirazxmondal**
Eddiehub image resized and added a new directory called images inside pages where I have saved the resized image! It fixes https://github.com/hasnainmakada-99/Open-Source-With-Hasnain/issues/39

### CODE REVIEW

**Comment by hasnainmakada-99** [comment]
Hey @miraz-mondal, please reference this pr with its corresponding issue

**Comment by mirazxmondal** [comment]
It fixes #39

**Comment by mirazxmondal** [comment]
@hasnainmakada-99 is this what referencing with a PR means to its corresponding issue? 

Please correct me if I am wrong

**Comment by hasnainmakada-99** [comment]
Mention in the description of your pr that which issue does it fixes, preceding with a hashtag (#)

**Comment by mirazxmondal** [comment]
Okay I did it. Could you check now

**Review by hasnainmakada-99 — APPROVED** [review]
Looks Good to me

**Comment by hasnainmakada-99** [comment]
@all-contributors, please add @miraz-mondal as a contributor of design

**Comment by hasnainmakada-99** [comment]
@all-contributors please add @miraz-mondal as a contributor of design

**Pull request merged**
