### PR TITLE
Added Resources in Web-development-resources.md file

### PR DESCRIPTION
**Pull request by SattyamSamania**
# 🛠️ Fixes issue #13
# 📇 Changes proposed - Added the Web Development for beginners resource in the web-development-resource.md file 
# ✅ Check List (Mark all the applicable boxes)

- [x ] My code follows the code style of this project.
- [x ] This PR does not contain plagiarized content.
- [x ] This PR contains changes in the documentation
- [x ] This PR contains changes in the Code of the project
- [x ] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots:
Screenshot (256)

### CODE REVIEW

**Review by hasnainmakada-99 — CHANGES_REQUESTED** [review]
This file is completely out of format @SattyamSamania , please format it as it was

**Comment by SattyamSamania** [comment]
> This file is completely out of format @SattyamSamania , please format it as it was

Understood. So i have to make another section of web development or simply put below the Git and Github resource?

**Comment by hasnainmakada-99** [comment]
> > This file is completely out of format @SattyamSamania , please format it as it was
> 
> Understood. So i have to make another section of web development or simply put below the Git and Github resource?

Just simply put below the git and github resource and format the table accorfing to that, remember the thumbnail size should be 320x180 px

**Comment by hasnainmakada-99** [comment]
Fill the PR template @SattyamSamania  properly

**Comment by hasnainmakada-99** [comment]
@SattyamSamania ?

**Comment by SattyamSamania** [comment]
> @SattyamSamania ?

I have made changes in the PR template and also changed the Screenshot. Let me know if any other correction is required.

**Review by hasnainmakada-99 — APPROVED** [review]
LGTM

**Comment by hasnainmakada-99** [comment]
@all-contributors please add @SattyamSamania as contributor of content

**Pull request merged**
